### ISSUE TITLE
It should be possible to set bitrate range for a resolution

### ISSUE THREAD

**Issue by oscnord** [Eyevinn/autovmaf#37]
Currently all bitrates will be encoded and measured for all resolutions. It would be nice to be able to set a bitrate range for a resolution (optional).

Proposal: 

```typescript
{
    name: "MyVMAFmeasurements",
    pipeline: "pipeline.yml",
    encodingProfile: "profile.json",
    reference: "reference.mp4",
    models: ["HD", "PhoneHD"],
    resolutions: [
    { 
       width: 1280, 
       height: 720,
       range: {
         min: 500000,
         max: 600000
       }    
    }],
    bitrates: [500000, 600000, 800000],
    method: "bruteForce"
}
```

**Comment by jonathanwalter** [comment]
How would this work in `job.yml`? 🤔 

```yml
name: job-name
pipeline: pipeline.yml
encodingProfile: encoding-profile.json
reference: reference.mp4
models:
  - HD
  - PhoneHD
resolutions:
  - 1280x720:500000-600000
```
